//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmisWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medico
    {
        public int Id { get; set; }
        public string Cpf { get; set; }
        public string Crm { get; set; }
        public string uf { get; set; }
        public string EnderecoConsultorio { get; set; }
        public int IdPessoa { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
    }
}
