//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmisWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.Glicemia = new HashSet<Glicemia>();
            this.Refeicao = new HashSet<Refeicao>();
        }
    
        public int Id { get; set; }
        public string Peso { get; set; }
        public string Altura { get; set; }
        public string TipoDiabetes { get; set; }
        public string Terapia { get; set; }
        public System.DateTime Diagnostico { get; set; }
        public int ObjetivoPreRefeicao { get; set; }
        public int ObjetivoPosRefeicao { get; set; }
        public int ObjetivoAntesDormir { get; set; }
        public int IdPessoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Glicemia> Glicemia { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Refeicao> Refeicao { get; set; }
    }
}
