//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmisWebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente_Vinculado
    {
        public int Id { get; set; }
        public Nullable<int> IdPaciente { get; set; }
        public Nullable<int> IdMedico { get; set; }
    
        public virtual Medico Medico { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
